from dataclasses import dataclass, field
from typing import FrozenSet, Optional


@dataclass(frozen=True)
class ModeDef:
    code: str
    name: str
    description: str
    attr_name: str
    families: FrozenSet[str] = field(default_factory=frozenset)
    cross_om_grouping: bool = False
    cross_om_matching: bool = False
    source_filter: bool = False
    strategy_key: Optional[str] = None
    receive_site_limit: bool = False
    extra_ui_options: FrozenSet[str] = field(default_factory=frozenset)
    required_columns: FrozenSet[str] = field(default_factory=frozenset)
    source_method: Optional[str] = None
    dest_method: Optional[str] = None


MODE_REGISTRY: dict[str, ModeDef] = {
    "A": ModeDef(
        code="A",
        name="保守轉貨",
        description="保守轉貨模式：20%上限，嚴格保持Safety Stock",
        attr_name="A",
    ),
    "B": ModeDef(
        code="B",
        name="加強轉貨",
        description="加強轉貨模式：50%上限，可低於Safety Stock",
        attr_name="B",
    ),
    "B2": ModeDef(
        code="B2",
        name="附加B(特別模式)",
        description="B特別模式：Type L低銷店全轉出，B模式規則",
        attr_name="B2",
        families=frozenset({"b_special"}),
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B2a": ModeDef(
        code="B2a",
        name="附加B2a(T不出貨)",
        description="B2特別模式：T類店舖不出貨",
        attr_name="B2a",
        families=frozenset({"b_special", "b_tourist_no_source"}),
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B2L": ModeDef(
        code="B2L",
        name="附加B2L(L保留2)",
        description="B2L模式：L低銷店保留2件後轉出",
        attr_name="B2L",
        families=frozenset({"b_special", "b_l_retain"}),
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B2La": ModeDef(
        code="B2La",
        name="附加B2La(L2+T不出)",
        description="B2La模式：L保留2件，T不出貨",
        attr_name="B2La",
        families=frozenset({"b_special", "b_tourist_no_source", "b_l_retain"}),
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B3": ModeDef(
        code="B3",
        name="附加B3(跨OM)",
        description="B3跨OM模式：跨OM匹配，HD/Windy限制",
        attr_name="B3",
        families=frozenset({"b_special", "b3_family"}),
        cross_om_grouping=True,
        cross_om_matching=True,
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B3a": ModeDef(
        code="B3a",
        name="附加B3a(跨OM+T不出)",
        description="B3a模式：跨OM，T不出貨",
        attr_name="B3a",
        families=frozenset({"b_special", "b3_family", "b_tourist_no_source"}),
        cross_om_grouping=True,
        cross_om_matching=True,
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B3L": ModeDef(
        code="B3L",
        name="附加B3L(跨OM+L2)",
        description="B3L模式：跨OM，L保留2件",
        attr_name="B3L",
        families=frozenset({"b_special", "b3_family", "b_l_retain"}),
        cross_om_grouping=True,
        cross_om_matching=True,
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "B3La": ModeDef(
        code="B3La",
        name="附加B3La(跨OM+L2+T)",
        description="B3La模式：跨OM，L保留2件，T不出貨",
        attr_name="B3La",
        families=frozenset({"b_special", "b3_family", "b_tourist_no_source", "b_l_retain"}),
        cross_om_grouping=True,
        cross_om_matching=True,
        strategy_key="b_special",
        receive_site_limit=True,
        dest_method="_dests_b_special",
    ),
    "C": ModeDef(
        code="C",
        name="重點補0",
        description="重點補0模式：30%/3上限，優先補零庫存店",
        attr_name="C",
    ),
    "C1": ModeDef(
        code="C1",
        name="重點補0-只補0/1",
        description="C1模式：只補零庫存，庫存>2才轉出，至少2件",
        attr_name="C1",
        dest_method="_dests_c1_mode",
    ),
    "C2": ModeDef(
        code="C2",
        name="附加C2(跨OM)",
        description="C2跨OM模式：跨OM重點補0",
        attr_name="C2",
        cross_om_grouping=True,
        cross_om_matching=True,
        source_filter=True,
        strategy_key="c2_mode",
    ),
    "D": ModeDef(
        code="D",
        name="清貨轉貨",
        description="清貨轉貨模式：無銷售ND全轉出",
        attr_name="D",
        families=frozenset({"d_family"}),
        dest_method="_dests_d_mode",
    ),
    "D2": ModeDef(
        code="D2",
        name="清貨轉貨(ND限定)",
        description="D2模式：僅無銷售ND可轉出",
        attr_name="D2",
        families=frozenset({"d_family"}),
        dest_method="_dests_d_mode",
    ),
    "E1": ModeDef(
        code="E1",
        name="強制轉出",
        description="E1模式：ALL標記貨品強制轉出（同OM）",
        attr_name="E1",
        source_filter=True,
        strategy_key="e1_mode",
        receive_site_limit=True,
        required_columns=frozenset({"ALL"}),
        source_method="_sources_e_mode",
        dest_method="_dests_e_mode",
    ),
    "E1b": ModeDef(
        code="E1b",
        name="強制轉出(優先類型)",
        description="E1b模式：ALL標記，優先T/M店接收",
        attr_name="E1b",
        source_filter=True,
        strategy_key="e1_mode",
        receive_site_limit=True,
        required_columns=frozenset({"ALL"}),
        source_method="_sources_e_mode",
        dest_method="_dests_e_mode",
    ),
    "E2": ModeDef(
        code="E2",
        name="強制轉出(跨OM)",
        description="E2模式：跨OM強制轉出，3-Phase回退機制",
        attr_name="E2",
        cross_om_grouping=True,
        cross_om_matching=True,
        source_filter=True,
        strategy_key="e2_mode",
        receive_site_limit=True,
        required_columns=frozenset({"ALL"}),
        source_method="_sources_e_mode",
        dest_method="_dests_e_mode",
    ),
    "F": ModeDef(
        code="F",
        name="目標優化",
        description="F模式：Target驅動，跨OM，含補0邏輯",
        attr_name="F",
        cross_om_grouping=True,
        cross_om_matching=True,
        source_filter=True,
        strategy_key="f_mode",
        source_method="_sources_f_mode",
        dest_method="_dests_f_mode",
    ),
    "F2": ModeDef(
        code="F2",
        name="F指定模式",
        description="F2模式：Target驅動無補0，HD可轉出選項",
        attr_name="F2",
        cross_om_grouping=True,
        cross_om_matching=True,
        source_filter=True,
        strategy_key="f_mode",
        extra_ui_options=frozenset({"f2_hd_transfer"}),
        source_method="_sources_f_mode",
        dest_method="_dests_f_mode",
    ),
    "ND1": ModeDef(
        code="ND1",
        name="ND同OM轉貨",
        description="ND1模式：ND可接收，同OM智能分配",
        attr_name="ND1",
        families=frozenset({"nd_transfer"}),
        source_filter=True,
        strategy_key="nd_mode",
        receive_site_limit=True,
        source_method="_sources_nd_mode",
        dest_method="_dests_nd_mode",
    ),
    "ND2": ModeDef(
        code="ND2",
        name="ND混合OM轉貨",
        description="ND2模式：跨OM ND智能分配",
        attr_name="ND2",
        families=frozenset({"nd_transfer"}),
        cross_om_grouping=True,
        cross_om_matching=True,
        source_filter=True,
        strategy_key="nd_mode",
        receive_site_limit=True,
        source_method="_sources_nd_mode",
        dest_method="_dests_nd_mode",
    ),
    "簡同": ModeDef(
        code="簡同",
        name="精簡SKU(限同OM)",
        description="精簡SKU模式：Cap=2倍Safety或Last2Month",
        attr_name="簡同",
        families=frozenset({"simplified_sku"}),
        source_filter=True,
        strategy_key="simplified_sku",
        source_method="_sources_simplified_sku",
        dest_method="_dests_simplified_sku",
    ),
    "簡跨": ModeDef(
        code="簡跨",
        name="精簡SKU(跨OM)",
        description="精簡SKU跨OM模式：跨OM Cap限制",
        attr_name="簡跨",
        families=frozenset({"simplified_sku"}),
        cross_om_matching=True,
        source_filter=True,
        strategy_key="simplified_sku",
        source_method="_sources_simplified_sku",
        dest_method="_dests_simplified_sku",
    ),
}
